export const Constants = {
    platform: {
        Enums: {
            attribution_source: [
                "DIRECT",
                "PARTNER",
                "REFERRAL",
                "INBOUND",
                "CAMPAIGN",
            ],
            billing_interval: ["MONTHLY", "QUARTERLY", "YEARLY", "ONE_TIME"],
            charge_kind: [
                "LICENSE",
                "PARTNER_BASE_LICENSE",
                "TENANT_LICENSE",
                "IMPLEMENTATION_FEE",
                "INFRASTRUCTURE_FEE",
                "SUPPORT_FEE",
                "ADDON",
                "PROFESSIONAL_SERVICES",
                "DISCOUNT",
            ],
            commission_basis: [
                "COLLECTED_LICENSE",
                "COLLECTED_IMPLEMENTATION",
                "COLLECTED_ANY",
                "FIXED_AMOUNT",
            ],
            commission_status: ["PENDING", "ELIGIBLE", "ACCRUED", "PAID", "VOID"],
            cost_category: [
                "DATABASE",
                "COMPUTE",
                "STORAGE",
                "BANDWIDTH",
                "MESSAGING",
                "FRONTEND_HOSTING",
                "DOMAIN",
                "SUPPORT",
                "DEDICATED_INFRA",
                "THIRD_PARTY",
                "ADMIN_MANUAL",
            ],
            cost_scope: [
                "PLATFORM",
                "PRODUCT",
                "ORGANIZATION",
                "TENANT",
                "DEPLOYMENT_TARGET",
            ],
            deployment_mode: ["SHARED", "PARTNER_DEDICATED", "TENANT_DEDICATED"],
            entity_status: ["ACTIVE", "INACTIVE", "SUSPENDED", "ARCHIVED"],
            environment_kind: ["DEMO", "TRIAL", "PRODUCTION", "SANDBOX"],
            infra_provider: ["SUPABASE", "AWS", "AZURE", "GCP", "ON_PREMISE"],
            invoice_status: [
                "DRAFT",
                "ISSUED",
                "PARTIALLY_PAID",
                "PAID",
                "VOID",
                "UNCOLLECTIBLE",
            ],
            org_capability: ["PARTNER", "RESELLER", "CONSULTING", "CUSTOMER"],
            org_kind: ["PLATFORM", "COMPANY"],
            org_relationship_type: ["MANAGES", "RESELLS_TO", "SUBCONTRACTS"],
            org_role: [
                "PARTNER_ADMIN",
                "PARTNER_SALES",
                "PARTNER_SUPPORT",
                "ORG_ADMIN",
                "ORG_VIEWER",
            ],
            payment_status: ["PENDING", "CONFIRMED", "REVERSED"],
            platform_role: ["EBIM_SUPER_ADMIN", "EBIM_PRODUCT_ADMIN", "EBIM_FINANCE"],
            provisioning_action: [
                "CREATE_TENANT_SPACE",
                "CREATE_DEDICATED_TARGET",
                "ATTACH_TENANT_TO_TARGET",
                "SUSPEND_TENANT",
                "RESUME_TENANT",
                "DECOMMISSION_TENANT",
            ],
            provisioning_status: [
                "PENDING",
                "VALIDATING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
            ],
            sales_agent_type: ["EBIM_INTERNAL", "INDEPENDENT", "PARTNER_AGENT"],
            settlement_status: ["OPEN", "APPROVED", "PAID", "CANCELLED"],
            subscription_status: [
                "DRAFT",
                "ACTIVE",
                "PAST_DUE",
                "PAUSED",
                "CANCELLED",
            ],
            tenant_role: ["TENANT_ADMIN", "TENANT_USER"],
            tenant_status: ["PENDING", "ACTIVE", "SUSPENDED", "CHURNED", "ARCHIVED"],
            tenant_type: ["DEMO", "TRIAL", "PRODUCTION", "SANDBOX"],
        },
    },
};
